version: '2'
services:

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql
      - redis:redis
      - rabbitmq:rabbitmq
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  php:
    build: .
    working_dir: /var/www
    volumes_from:
      - code

  mysql:
    image: mysql
    ports:
      - "33061:3306"
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"

  code:
    image: busybox
    volumes:
      - ./www:/var/www